### ISSUE TITLE
Adding an Appointment Request Form to the Doctor's Appointment Page in Rehabify

### ISSUE THREAD

**Issue by IkkiOcean** [Ratnesh-Team/Rehabify#103]
### Description
Currently, when a user clicks on a doctor's card, they are redirected to WhatsApp. We want to enhance the user experience by allowing users to submit an appointment request form directly through the doctor's appointment page instead of being redirected to WhatsApp. This feature will streamline the appointment scheduling process and keep users within the app.

### Proposed Solution
- Create an appointment request form that includes the following fields:
   - Patient's Name
   - Contact Information (Phone Number, Email)
   - Preferred Appointment Date and Time
   - Reason for Appointment (Optional)
   - Additional Comments (Optional)

### Benefits
- Improves user experience by keeping users within the app.
- Facilitates easier management of appointment requests for both users and doctors.
- Reduces reliance on external messaging platforms for appointment scheduling.

### Additional Notes
- Ensure that form validation is implemented.
- I will be working on the frontend only.

**Comment by Vasist10** [comment]
can you assign me this issue?

**Comment by ratnesh-maurya** [comment]
sure go ahead
