### ISSUE TITLE
User Registration Error in Manage NMK Section Due to Circular JSON Structure and CORS Policy

### ISSUE THREAD

**Issue by amitb0ra** [Ratnesh-Team/Rehabify#106]
**Describe the bug**
When trying to add a user in the "Manage NMK" section, an error occurs due to circular JSON structure and CORS policy restrictions, resulting in a failed API request.

**To Reproduce**
1. Go to the "Manage NMK" section and add user.
2. Fill out the user registration form with valid data.
3. Click on the 'Register' button.
4. Observe the error messages in the console.

**Expected behavior**
The form should successfully convert the data to JSON and send a POST request without any errors. The API should allow cross-origin requests from the specified origin.

**Screenshots**
![image](https://github.com/user-attachments/assets/b7a7c14b-41ce-4274-95e7-bfab56248f33)

**Comment by ratnesh-maurya** [comment]
hi @amitb0ra ,
its due to someone didn't chnage the backend url in code ,
its not bug , 
Thanks for informing

**Comment by amitb0ra** [comment]
okay, can i fix that?

**Comment by ratnesh-maurya** [comment]
it will be just url change, i don't want someone to do this just for sake of contribution.
Thanks for pointing out the issue
