### ISSUE TITLE
[FEATURE] Fixing the CARD DIV to make the UI Better

### ISSUE THREAD

**Issue by HemantBatra873** [Ratnesh-Team/Rehabify#107]
**Problem**
The card div that holds all the cards like NMK's and doctor cards should hold 4 cards in the top and bottom . But in the bottom it has only 2 cards which is looking odd. Also the card div should have the same size and position of page number in the bottom left but right now its according to the size of the card div .

---
![rehabify1](https://github.com/user-attachments/assets/f3eea0d9-5d94-4fc1-8b40-8f2aab1a4340)

![rehabify2](https://github.com/user-attachments/assets/baeac2d5-1380-4509-9ad9-a17205382f44)

---

**Solution**
I'll correct the card div component and fix the size in all the pages . Making the UI looking more clean and appealing .

**Please assign this to me under hacktoberfest-accepted and gssoc .**

**Comment by tarunkumar2005** [comment]
I can also contribute to this assign this to me under gssoc 2024 ext and hacktoberfest.

**Comment by ratnesh-maurya** [comment]
sure go ahead
