### ISSUE TITLE
Fixing the ui issues while adding a new user through the form manage NMK

### ISSUE THREAD

**Issue by tarunkumar2005** [Ratnesh-Team/Rehabify#110]
![image](https://github.com/user-attachments/assets/103e6dc6-263b-46d7-ab18-30cd793c96cd)

Fixing the ui issues while adding a new user through the form manage NMK. So the thing is that the form is not good to look and overflowing and many issue i want to improve its ui and make it more impresive and amazing to look with professional touch in it with the consistent theme of the website.

@ratnesh-maurya Assign this to me under gssoc 2024 ext and hacktoberfest i will work on this issue.

**Comment by ratnesh-maurya** [comment]
hi @tarunkumar2005  this issue is being and someone is working on it
