### ISSUE TITLE
Add Validation for User Registration Form in Manage NMK Page

### ISSUE THREAD

**Issue by Akkash20** [Ratnesh-Team/Rehabify#112]
**Description:** The user registration form on the **Manage NMK page** currently lacks validation and accepts incorrect values such as:

1) Numbers in the name field.
2) Negative values for age.
3) Age values as low as 1 or 2, where addiction is not a realistic concern.
4) Negative values for addiction duration.

![Screenshot_20241017_000118 (2)](https://github.com/user-attachments/assets/0de20de3-47e0-4d7d-a9d4-0db74c3b5cf2)

These fields need proper validation to ensure accurate data input. I would like to work on implementing these validations. 

### Can this issue be assigned to me?

**Comment by ratnesh-maurya** [comment]
yes sure go ahead
