### ISSUE TITLE
Addition of feedback form

### ISSUE THREAD

**Issue by Mahak-Agrawal-304** [Ratnesh-Team/Rehabify#114]
**Is your feature request related to a problem? Please describe.**
Since it is a non-profitable organisation, people generally find it difficult to believe if the site will genuinely help them or not. 

**Describe the solution you'd like**
To win public trust, I believe we should add a review section as well where people and recovered patients and family members can share their experiences with everyone. We can also display it on our site.

**Additional context**
Add sections like:
![Screenshot (3089)](https://github.com/user-attachments/assets/d6fbbf32-80a2-4286-a67f-87c24ae37580)
![Screenshot (3088)](https://github.com/user-attachments/assets/d361f8c8-9313-4fea-80b5-cfcf2e889bcb)

I am a GSSoC'24 Ext. contributor

**Comment by ratnesh-maurya** [comment]
refer to this #51

**Comment by Mahak-Agrawal-304** [comment]
Alright @ratnesh-maurya
