### ISSUE TITLE
 Implement Custom Scroll Bar and Progress Bar for Rehabify Website

### ISSUE THREAD

**Issue by srishti023** [Ratnesh-Team/Rehabify#116]
Description:

Scroll Bar: Create an eye-catching, custom-designed scroll bar using CSS, with a gradient color scheme and modern styling.

Progress Bar: Add a dynamic progress bar that tracks the user's scroll position across the page, providing a visual indicator of how much content has been viewed.

These enhancements will elevate the user experience by making the interface more engaging and visually appealing.

**Comment by ratnesh-maurya** [comment]
#80  kindly refer to his
