### ISSUE TITLE
Image Change

### ISSUE THREAD

**Issue by daky2024** [Ratnesh-Team/Rehabify#117]
**Image not matching with description**

**To Reproduce**
1. Go to 'home remedies'
2. See error

**Expected behavior**
I want to enhance

 the image as under home remedies section as they do not match description ex Regular exercise

**Screenshots**
![Screenshot_18-10-2024_142431_rehabify ratn tech](https://github.com/user-attachments/assets/f5aa4f2c-057a-4294-869c-5a53a62fd179)

**Desktop (please complete the following information):**
 - OS: [window 11]
 - Browser [Microsoft edge]

**Smartphone (please complete the following information):**
 - Device: [realme 9pro]
 - OS: [UI 4.0]
 - Browser [chrome]
 - Version [5.43]

**Comment by ratnesh-maurya** [comment]
i dont thing its  needed because we are displaying the fake data only
