### ISSUE TITLE
The implementation of a Testimonial card feature.

### ISSUE THREAD

**Issue by RabdeepKaur** [Ratnesh-Team/Rehabify#129]
Feature :Testimonail card 
I would like to propose the implementation of a testimonial card feature. This feature will allow users to display testimonials in a visually appealing card format, enhancing user engagement and credibility.

![Screenshot 2024-10-21 093235](https://github.com/user-attachments/assets/87c391a6-b175-4f8d-bbd1-2366505c68ad)
 Maybe a card like these just above the Home Remedies , using the same color as database background.

Assign this issue to me if you want me implement this  and please add Ggsoc-Extend and Hacktoberfest label

**Comment by RabdeepKaur** [comment]
@ratnesh-maurya  assign this issue to me and to let me know if you want some UI change in the feature

**Comment by ratnesh-maurya** [comment]
sure go ahead
