### ISSUE TITLE
Dockerize backend 

### ISSUE THREAD

**Issue by sanjay14073** [Ratnesh-Team/Rehabify#133]
It would be helpful for dev's who dont have go and mongo installed

The proposed solution is to dockerize the complete backend also we can bind a volume for local mongodb setup.in case a url to the mongo is provided he still can set the env variables and run only the go Docker file else he can run the docker-compose up commad to start all the services.

**Comment by sanjay14073** [comment]
@ratnesh-maurya  can you assign this to me under the hacktoberfest-accepted and gssoc-ext labels

**Comment by ratnesh-maurya** [comment]
sure

**Comment by ratnesh-maurya** [comment]
> I would like to work on this, kindly assign me this issue.
this issue is resolved
