### ISSUE TITLE
IMPROVE TREATMENT CENTER PAGE 

### ISSUE THREAD

**Issue by shubhagarwal1** [Ratnesh-Team/Rehabify#141]
- IMPROVE CARD DESIGN 
- IMPROVE GRID MANGAEMENT 
<img width="1432" alt="Screenshot 2024-10-25 at 5 35 22 AM" src="https://github.com/user-attachments/assets/5e44bf33-b573-41aa-a3a4-8bdc63d9ff50">

**Comment by ratnesh-maurya** [comment]
hi @shubhagarwal1  we are aware of this behaviour and one person is working on the same

**Comment by shubhagarwal1** [comment]
> hi @shubhagarwal1 we are aware of this behaviour and one person is working on the same

Hey @ratnesh-maurya, can you tell me something that i can work on,i would love to wrok on the project

**Comment by ratnesh-maurya** [comment]
try to find a bug or ui issue then i can assign that , currently not having any plan for new features
