### ISSUE TITLE
Expand Home Remedies Section

### ISSUE THREAD

**Issue by AnushkaChouhan25** [Ratnesh-Team/Rehabify#148]
I would like to propose adding more home remedies. This enhancement will provide users with a wider range of options and information on effective home treatments, enriching the platform's content and user experience.

### Suggested Changes

- Research and compile additional home remedies that are relevant to the project’s focus.
- Ensure that the new remedies are presented with clear descriptions and usage instructions.
- Consider categorizing remedies based on conditions or benefits for better navigation.

![image](https://github.com/user-attachments/assets/e7e4c8f6-ff97-4297-8378-ae64c8594f53)

**Comment by ratnesh-maurya** [comment]
you can work on one issue at a time and same issue is also opened by another contributor
