### ISSUE TITLE
Add Stargazers and Forkers Profiles to README.md ✨ 

### ISSUE THREAD

**Issue by AnushkaChouhan25** [Ratnesh-Team/Rehabify#150]
**Is your feature request related to a problem? Please describe.**
To showcase community engagement and make the project more interactive, add the stargazers and workers profiles to the README.md, as shown in the screenshot.

![image](https://github.com/user-attachments/assets/4da5c285-87c6-49f9-91c5-9007f0c2e94b)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ratnesh-maurya** [comment]
Not required for now it does't add any value to readme
