### ISSUE TITLE
 Update Swagger Documentation for Backend API

### ISSUE THREAD

**Issue by ratnesh-maurya** [Ratnesh-Team/Rehabify#38]
**Description:**  
We need to update the Swagger documentation for our backend API to ensure it accurately reflects the current API endpoints, request/response formats, and overall functionality. Proper documentation is crucial for improving developer experience and facilitating easier integration .

**Current Documentation:**  
[Swagger UI Documentation](https://apiforrehabify.prod.psi.initz.run/swagger-ui/index.html)

**Reference Guide:**  
For implementation details, please refer to the following guide:  
[How to Add Swagger in Golang Gin](https://lemoncode21.medium.com/how-to-add-swagger-in-golang-gin-6932e8076ec0)

**Objectives:**
1. **Review Current Documentation:** Evaluate the existing Swagger documentation for accuracy and completeness.
  
2. **Update Endpoints:** Ensure all current API endpoints are documented, including any new additions or modifications.
  
3. **Define Request and Response Models:** Clearly define and document request and response models for each endpoint, including parameter descriptions, data types, and example values.

4. **Add Annotations:** Utilize appropriate annotations in the codebase to generate updated Swagger documentation automatically.

5. **Testing:** Verify that the updated Swagger documentation is functional and accessible, with all endpoints returning the correct data.

**Requirements:**
- Familiarity with Swagger and API documentation.
- Experience with Golang and the Gin framework.
- Attention to detail to ensure all endpoints are accurately documented.

**Priority:** High

**Comment by ratnesh-maurya** [comment]
sure  , go ahead

**Comment by ratnesh-maurya** [comment]
@Charul00 are you working on it

**Comment by Charul00** [comment]
not yet started

**Comment by ratnesh-maurya** [comment]
@Charul00 any progress

**Comment by sanjay14073** [comment]
@ratnesh-maurya i would like to work on it

**Comment by ratnesh-maurya** [comment]
sure @sanjay14073 go ahead

**Comment by sanjay14073** [comment]
@ratnesh-maurya  yes I will i couldn't do it as I was unwell

**Comment by ratnesh-maurya** [comment]
> i want to work on this issue .assign me this project

this issue is resolved
