### ISSUE TITLE
Improving Readme.md File slight for a better reead

### ISSUE THREAD

**Issue by rishyym0927** [Ratnesh-Team/Rehabify#40]
Hey I think that the readme.md file is not very perfect I can add some elements to it from my side.

Please label it under gssoc and assign me this issue

**Comment by ratnesh-maurya** [comment]
@rishyym0927 

### Please mention the following in the README.md:

- For contributing to this repository, make sure to create a new branch and raise a pull request to the **develop** branch.

**Comment by ratnesh-maurya** [comment]
@rishyym0927  are you working on it

**Comment by rishyym0927** [comment]
yes

**Comment by sakshamsaraf23** [comment]
@ratnesh-maurya please assign me the task of adding contributors

**Comment by rishyym0927** [comment]
im working on it, give me some more time

**Comment by sakshamsaraf23** [comment]
ok buddy

**Comment by ratnesh-maurya** [comment]
@rishyym0927 i am assigning this issue to @sakshamsaraf23  as you are not active from last 4 days

**Comment by sakshamsaraf23** [comment]
@ratnesh-maurya done

**Comment by ratnesh-maurya** [comment]
closing as the readme file is updated
