### ISSUE TITLE
Missing ratelimiter, logger middlewaraes

### ISSUE THREAD

**Issue by toastsandwich** [Ratnesh-Team/Rehabify#41]
Rate limiter will prevent ddos attacks and will prevent server from over loading, and logger middleware will help in debugging.

**Comment by toastsandwich** [comment]
can you assign this issue to me ??

**Comment by ratnesh-maurya** [comment]
sure go ahead

**Comment by toastsandwich** [comment]
@ratnesh-maurya I have submitted the PR please add it for gssoc and hacktober, with tag as hacktober-accepted and can you also add hacktober in your github repository.

**Comment by ratnesh-maurya** [comment]
sure , @toastsandwich can you raise PR for develop branch, and add  me as a reviewer.

**Comment by toastsandwich** [comment]
@ratnesh-maurya i have created the pr

**Comment by ratnesh-maurya** [comment]
@toastsandwich  Thanks for your Contribution . you commits are now in production cheers 🥂

**Comment by toastsandwich** [comment]
@ratnesh-maurya, i cannot find myself as a contibutor for this repo
