### ISSUE TITLE
404 Error

### ISSUE THREAD

**Issue by yasheela-alla** [Ratnesh-Team/Rehabify#42]
**Description:**

I am currently experiencing a 404 error when trying to access the server endpoint in my backend application. Below is the relevant console output captured during my testing.

**Console Output:**
![image](https://github.com/user-attachments/assets/1e4faeff-2084-48fe-9c65-2c1c0bd1e2c1)
![image](https://github.com/user-attachments/assets/4200c70d-7c00-46c8-80e1-e5ba649ad3b8)

**Expected Behavior:**
- When I send a GET request to the `/home-remedies` endpoint, I expect a successful response with the corresponding data.

**Actual Behavior:**
- Instead of a successful response, I am receiving a 404 error, indicating that the resource could not be found.

**inspecting the console output**
![image](https://github.com/user-attachments/assets/9b0b490d-675b-498b-9117-f1d82ee450a2)

**Steps to Reproduce:**
1. Start the server.
2. Send a GET request to `http://localhost:3000/home-remedies`.
3. Observe the 404 error in the console.

**Environment:**
- Backend Framework: Gin (Go)
- Database: MongoDB
- Operating System: Windows

**Additional Information:**
- The server is running in debug mode, and I've verified that the endpoint is defined in the routes.

**Comment by toastsandwich** [comment]
are you logged in ??
