### ISSUE TITLE
Mobile Responsiveness Issues

### ISSUE THREAD

**Issue by pranavbafna586** [Ratnesh-Team/Rehabify#50]
**Description:**
Some elements are not adjusting correctly on mobile devices, causing navigation problems and content being cut off on smaller screens.

**Steps to Reproduce:**
1. Access [[Home Page](https://rehabify.ratn.tech/home)] on a mobile device.
2. Resize the browser window to simulate different screen sizes.
3. Observe elements that don't scale properly.

**Expected Behavior:**
Pages should be fully responsive and adapt smoothly to various screen sizes.

**Priority:** High

Could you please assign this issue to me under GSSOC'24 extd?

**Comment by ratnesh-maurya** [comment]
Thank you for bringing this issue to our attention! We are aware of the behavior and would definitely like to see improvements in mobile responsiveness. We appreciate your willingness to work on it, and we will gladly accept the changes.

I’ve labeled the issue under GSSOC'24 Extended and assigned it to you. Looking forward to your contribution!

**Comment by ratnesh-maurya** [comment]
Hi @pranavbafna586 any updates, if you are facing any problem you can ask

**Comment by pranavbafna586** [comment]
yes sir woking on it actually got a lot of errors will update it soon

**Comment by ratnesh-maurya** [comment]
Sure take your time just keep me updated

**Comment by syedfardeenjeelani** [comment]
@ratnesh-maurya kindly assign it to me

**Comment by ratnesh-maurya** [comment]
sure @syedfardeenjeelani

**Comment by syedfardeenjeelani** [comment]
@ratnesh-maurya  please review my pr
