### ISSUE TITLE
 User Feedback System for Reporting Issues and Suggesting Improvements

### ISSUE THREAD

**Issue by 0xPratikPatil** [Ratnesh-Team/Rehabify#51]
**Is your feature request related to a problem?** 
Yes, there is currently no way for users to provide feedback or report issues on the platform. This lack of a feedback system makes it challenging to identify user concerns and opportunities for improvement, limiting active user engagement.

**Describe the solution you'd like:**
 Implement a feedback system allowing users to report issues or suggest improvements directly on the site, promoting active user engagement. This system would collect feedback in real-time and notify the platform administrators for review and action.

**Describe alternatives you've considered:**
Alternatively, we could create a separate contact form or use third-party feedback tools like Google Forms or SurveyMonkey. However, an integrated system will provide a more seamless experience, ensuring users stay engaged on the platform.

**Additional context:**
 This feature will be particularly useful for improving platform usability and gathering insights from users of rehabilitation and Nasha Mukti Kendra centers. Screenshots of potential UI for the feedback system can be attached here for reference.

Could you please assign this issue to me under GSSOC'24 extd?

**Comment by ratnesh-maurya** [comment]
Thank you for the suggestion! While a feedback system is a good idea, we're not prioritizing it at the moment.
