### ISSUE TITLE
Integrate Zap Logger for Enhanced Request/Response Logging

### ISSUE THREAD

**Issue by rishyym0927** [Ratnesh-Team/Rehabify#56]
**Is your feature request related to a problem? Please describe.**  
Currently, there is no structured logging implemented in the route handling of our application. This makes it challenging to debug issues and track requests/responses, especially when trying to identify errors or monitor the application's behavior. I'm always frustrated when I can't find sufficient information in the logs to troubleshoot problems effectively.

**Describe the solution you'd like**  
I would like to implement Zap logging in the `routes/routes.go` file to enhance our logging capabilities. This should include logging relevant information such as incoming requests, response statuses, and any errors that occur during the request handling process. For example, each route handler should log when a request is received, and the status of the response (e.g., 200 OK, 404 Not Found, etc.).

**Describe alternatives you've considered**  
As an alternative, we could continue using the default logging provided by Gin, but it lacks the structured and customizable features that Zap offers. Additionally, we could explore other logging libraries, but Zap is known for its performance and structured logging, which aligns with our application's needs.

**Additional context**  
Implementing Zap will not only help in debugging but also in monitoring the application's health and usage patterns over time. It would be beneficial for all team members to have access to structured logs that provide insights into the application's operation. 

Please assign this issue to me and label it under gssoc level3

**Comment by ratnesh-maurya** [comment]
There is no need of Zap logger , gin has its own capability to log , and its implemented and it is in production 

![{0E25BE9B-2DCD-449F-95F7-3085C9CC2373}](https://github.com/user-attachments/assets/2f03ca4a-8550-4f6e-9ce4-6f01ee256775)

**Comment by rishyym0927** [comment]
I know but again as I said "As an alternative, we could continue using the default logging provided by Gin, but it lacks the structured and customizable features that Zap offers. Additionally, we could explore other logging libraries, but Zap is known for its performance and structured logging, which aligns with our application's needs." Thats why i thought why not to add it .
