### ISSUE TITLE
 Implement Performance Metrics for Golang Project

### ISSUE THREAD

**Issue by rishyym0927** [Ratnesh-Team/Rehabify#57]
**Is your feature request related to a problem? Please describe.**
Currently, our Golang project lacks performance metrics, making it difficult to identify bottlenecks and optimize resource usage. Without proper metrics, we might miss opportunities to enhance the application's performance, leading to potential scalability issues as usage grows.

**Describe the solution you'd like**
I propose implementing performance metrics using Go's built-in profiling tools and libraries like Prometheus. This will include:
- Adding benchmarking functions to measure performance.
- Implementing CPU and memory profiling using the `pprof` package.
- Exposing application metrics through an endpoint for monitoring.

**Describe alternatives you've considered**
Alternatives could include using other monitoring solutions or third-party libraries, but I believe using Go's native capabilities and Prometheus will be the most effective approach, providing both integration and flexibility.

**Additional context**
Adding performance metrics will not only enhance our understanding of the application but also allow us to respond proactively to performance-related issues. Implementing this will greatly benefit the development and maintenance of the project.

---

### Label:
- **gssoc-ext**
- **level-3**

**Comment by ratnesh-maurya** [comment]
sure go ahead

**Comment by ratnesh-maurya** [comment]
Any update @rishyym0927
