### ISSUE TITLE
Admin-Managed Home Remedies, Treatment Centers, and Doctor Appointment System

### ISSUE THREAD

**Issue by 0xPratikPatil** [Ratnesh-Team/Rehabify#58]
**Is your feature request related to a problem? Please describe.**  
We need to build the frontend functionality for admins to manage key platform features like home remedies, treatment center listings, and doctor appointments. Currently, there’s no interface for admins to easily add or control this information, making the platform less effective in serving users.

**Describe the solution you'd like**  
The solution involves building the frontend UI and forms that allow admins to manage the following:

1. **Home Remedies Section**  
   - Create a form where admins can input remedy details (name, ingredients, steps, safety notes). Admins will be able to add, edit, and delete remedies, and publish them for users to view.

2. **Treatment Centers Directory**  
   - Build a form for admins to register and update treatment centers. Inputs will include center name, address, types of treatments offered, facilities available, and certification status. The frontend should display a searchable and filterable directory for users.

3. **Doctor Appointment System**  
   - Develop an admin interface for managing doctor registrations and appointment slots. The form will include fields for doctor name, specialty, available time slots, and appointment details. Users can book appointments through the frontend, with admin approval or modification options.

**Frontend Considerations**  
- **Responsive UI**: The frontend needs to be responsive for both desktop and mobile platforms.
- **Form Validations**: Include proper form validation to ensure inputs are accurate and complete before submission.
- **Admin Dashboard**: Design a clean, intuitive dashboard for admins to manage remedies, centers, and appointments in one place.
- **Real-Time Updates**: Implement real-time updates to notify admins when new remedies, centers, or appointment requests are submitted.

**Describe alternatives you've considered**  
External tools could be used for these tasks, but integrating this functionality directly into the frontend will create a smoother and more cohesive admin experience. It allows admins to manage everything without leaving the platform.

**Additional context**  
This frontend implementation will empower admins to efficiently manage platform content and improve user engagement. It will also enhance the overall functionality by providing a seamless experience for users seeking remedies, treatment centers, or doctor appointments.

**Priority: High**
**Level: 3**
**Labels: gssoc-ext ,hacktoberfest**

**Comment by ratnesh-maurya** [comment]
## Observations & Recommendations

### 1. Admin Role:
![{67E3448B-0420-40E6-B291-8A6181F1DD3D}](https://github.com/user-attachments/assets/fe5f2956-5c07-497f-8b9e-466dde414e67)
When a user signs up and logs in with the **Admin** role, the following options are available:
   - Ability to add details for **NMK**.
   - Manage patients.

### 2. SuperAdmin Role:
When logged in with the **SuperAdmin** role, there is an option for **Approval**. However, I have identified a few gaps:
   - **Doctor Approval Flow**: Currently, there is no option to approve doctors. I recommend adding this flow on the approval page.
   - **Home Remedies Flow**: There is no flow for managing home remedies. You could add a tab that allows both **SuperAdmin** and **Admin** to add home remedies.

---

## Suggested Improvements

- [ ] **UI Enhancement**: Improve the user interface for **NMK registration**.
- [ ] **Doctor Approval**: For users with the **SuperAdmin** role, display doctors who are not verified and provide an option to approve them.
- [ ] **Home Remedies Flow**: Implement a feature where both **SuperAdmin** and **Admin** can add home remedies.
- [ ] **Doctor Appointment System**: Implement a doctor appointment system to allow scheduling of appointments efficiently.

---

These changes will enhance the system's functionality and user experience for both the **Admin** and **SuperAdmin** roles.

## Acknowledgment

If you'd like to collaborate or require any assistance in implementing these changes, feel free to reach out. I’d be happy to work together to improve the platform further.

**Comment by 0xPratikPatil** [comment]
1. There's an issue with the Doctor Appointment page—it’s appearing blank for all roles, including the Super Admin.

2. The 'Add User' floating modal isn't responsive and is overflowing outside the card. I'll work on fixing its responsiveness.

3. Since I'm not a Go developer, could you please assign me frontend tasks? I can deliver those quickly and keep things on track.

If it's okay, I’ll design all the forms, including:

1. A Home Remedies button with its form page or floating modal.

2. For the Doctor approval page, I can either add it as a separate page or integrate it into the Super Admin section.

3. For Booking Appointments, can I add a form to input patient info, previous reports, and schedule details?

4. Also for doctors, the appointment acceptance page and table their upcoming appointments

5. On the user side, I can build a table for appointments and their status.

**Comment by ratnesh-maurya** [comment]
Hello @0xPratikPatil can you share me the screenshots of doctor appointment page with network response

**Comment by ratnesh-maurya** [comment]
then we can discuss what you should work on
