### ISSUE TITLE
Descriptive Error Message for Slow Network Connections on Sign in

### ISSUE THREAD

**Issue by MutiatBash** [Ratnesh-Team/Rehabify#59]
**Describe the bug**

Currently, when I try to sign in and the network is slow or unstable, I receive a technical error message: "Axios error: Network Error". This message can be confusing for non-technical users, and the website does not provide guidance on what they should do next.

**To Reproduce**

1.  Try to sign in with a slow or unstable internet connection.
2. When the network request fails, the "Network Error" message from axios shows.
3. This does not provide a clear, user-friendly message to inform the user about the network issue.

**Expected behavior**

The site should display a clear and actionable message to the user when a network issue occurs. For example: "Connection is slow. Please check your internet connection and try again.

**Screenshots**
![IMG_7245](https://github.com/user-attachments/assets/385caa1a-19a4-4108-9414-b4375f3b3c15)

**Smartphone (please complete the following information):**
 - Device: iPhone 12
 - Browser - safari

I’d like to work on this issue as part of Hacktoberfest and GSSoC‘24 Extended

**Comment by ratnesh-maurya** [comment]
Thank you for reporting this issue! You're right, the technical error message can be confusing for non-technical users.

Additionally, I recommend handling this scenario consistently across all API requests, not just for the sign-in flow. This way, if any network issues occur while interacting with other parts of the site, users will receive the same clear and actionable message.

Let me know if you need assistance with implementing this across the platform!

**Comment by MutiatBash** [comment]
@ratnesh-maurya ….Hello, I’m having a bit of issue logging in on my local, I keep getting 404 error after trying all credentials provided. Do I need to also setup the backend to be able to run the project locally

**Comment by ratnesh-maurya** [comment]
Can you share me the .env variables that you are using .

**Comment by MutiatBash** [comment]
I've been able to create the env file, @ratnesh-maurya ......is there a specific message, you'll like me to display to handle this scenario

**Comment by ratnesh-maurya** [comment]
I didn't get you can you explain me what you actually asking for

**Comment by MutiatBash** [comment]
Should I use “Network error : Please try again” or “Network error: Please check your connection”

**Comment by ratnesh-maurya** [comment]
Network error: Please check your connection

**Comment by ratnesh-maurya** [comment]
#71

**Comment by ratnesh-maurya** [comment]
Great work @MutiatBash 🎉
