### ISSUE TITLE
UI and UX Issue while changing page

### ISSUE THREAD

**Issue by mohit-2003** [Ratnesh-Team/Rehabify#62]
When navigating from page 1 to page 2, there is a noticeable shift in the spacing between items. This causes a jarring experience for the user as elements move unexpectedly, leading to a poor UX.

Please see the attached video - 

https://github.com/user-attachments/assets/1b9cf613-8e6e-4640-a0c4-e1426108febd

**Comment by Koushikkd07** [comment]
I
 would like to work on this project. Please assign it to me.

**Comment by ratnesh-maurya** [comment]
Sure, but first find out the cause then I can assign you to fix that

**Comment by syedfardeenjeelani** [comment]
@ratnesh-maurya  if this issue still persists i can fix it

**Comment by syedfardeenjeelani** [comment]
please review my pr @ratnesh-maurya
