### ISSUE TITLE
Add contibutors to Readme.md

### ISSUE THREAD

**Issue by sakshamsaraf23** [Ratnesh-Team/Rehabify#63]
It lacks Contributors Profiles in Readme.md

It should be Like the image that I have shared
![373815323-76171289-5b05-48c4-a5be-dc8ac76d70cb](https://github.com/user-attachments/assets/753677a3-ff63-44c6-af60-2017c113c383)

Hey! @ratnesh-maurya can you assign me this issue under GSSoC-Extd and Hacktoberfest so that I can raise a PR.

I will add this type of Live Contributor Profile Photos in it

**Comment by ratnesh-maurya** [comment]
#40  similar issue is opened checkout that if you want to work on it
