### ISSUE TITLE
Addition of All Contributors Photos in Readme | Readme Updation

### ISSUE THREAD

**Issue by shubhagarwal1** [Ratnesh-Team/Rehabify#64]
We can add a file in workflows to add the contributors automatically to readme which basically enhaces the repo visibility
Hey @ratnesh-maurya  please assign this task to me with level tag

**Comment by ratnesh-maurya** [comment]
Hi @shubhagarwal1  I can assign you this issue but it's level will be 0 and there will be not any hacktober accepted tag .

**Comment by shubhagarwal1** [comment]
may i know the reason as this is also a complicated task adding automated contributor list to readme is not easy 
also why are you saying not accepted to the hacktoberfest or gssoc, it is an enhancement task which reduces the repetative adding manually 
may i know the reason

**Comment by ratnesh-maurya** [comment]
"[![Contributors](https://contrib.rocks/image?repo=ratnesh-maurya/your_contribution)](https://github.com/ratnesh-maurya/your_contribution/graphs/contributors)" 

This  line will do the thing of adding contributor in readme, And I am not marking it as hacktober-accepted because while a review hacktober eventually will reject this

**Comment by shubhagarwal1** [comment]
> ![Screenshot_2024-10-06-15-49-02-187_com.github.android-edit.jpg](https://private-user-images.githubusercontent.com/85143283/373938918-3b8dd012-1c74-45a8-8898-49a1cfe98e9a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyMTA0OTIsIm5iZiI6MTcyODIxMDE5MiwicGF0aCI6Ii84NTE0MzI4My8zNzM5Mzg5MTgtM2I4ZGQwMTItMWM3NC00NWE4LTg4OTgtNDlhMWNmZTk4ZTlhLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA2VDEwMjMxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY4ZGE0ZTYwNWRlNDNkMWEyMWUxMWY0M2Q2MGY5ZDA5ZWUyYzc5MjU5ZmQ1MWUwODIyOGI2OTNmYjFjODVjMjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.rxDOUI5pOEKMt01CF4KIELz6Q-TYkX3EMhUV2OjPuNE)
> 
> This line will do the thing of adding contributor in readme, And I am not marking it as hacktober-accepted because while a review hacktober eventually will reject this.

I understand please assign me something valuable that i can work on and that make valuable contribution to the repo

**Comment by ratnesh-maurya** [comment]
if you'd like to work on other issues, feel free to reach out—we're open for discussion. The goal of Hacktoberfest is to promote meaningful contributions to open-source projects, so if you're interested, we can find a suitable task for you. Let us know!

**Comment by ratnesh-maurya** [comment]
Sure, can you tell me your tech stack

**Comment by shubhagarwal1** [comment]
> Sure, can you tell me your tech stack

i can work on java, python and MERN

**Comment by ratnesh-maurya** [comment]
> > Sure, can you tell me your tech stack
> 
> i can work on java, python and MERN

okay,  i will se if there is anything you can do on frontend meanwhile you can also checkout platform  if any thing need improvement you can create issue
