### ISSUE TITLE
Make Explore More Button Neat

### ISSUE THREAD

**Issue by Rx-Metallica** [Ratnesh-Team/Rehabify#66]
Pls assign me

**Comment by ratnesh-maurya** [comment]
Hello @Rx-Metallica  can you explain what you actually want to do

**Comment by Rx-Metallica** [comment]
> Hello @Rx-Metallica  can you explain what you actually want to do 
> 

The buttons are not align in the box. in responsive too mode button are not aligned. If its design like that let it be i think it's fine.
