### ISSUE TITLE
Feature(Docker) : add production-ready Dockerfile Frontend

### ISSUE THREAD

**Issue by Arnab7456** [Ratnesh-Team/Rehabify#67]
1. Created a multi-stage Dockerfile to ensure small image size.
2. Provides a standardized way to build and run the frontend in production.
3. Reduces the risk of environment-specific issues.
4. Optimized for faster startup times and lower resource usage in production.

@ratnesh-maurya assign it to me

**Comment by ratnesh-maurya** [comment]
Thank you for raising this issue. I've already deployed the frontend without using the Dockerfile, and everything seems to be working fine so far. Could you clarify how you intended the Dockerfile to be used in the deployment process? I’d also appreciate more details on the specific environment-related issues or improvements (like faster startup times or lower resource usage) that you were expecting to address with it. This will help me ensure it’s utilized effectively, if necessary.

**Comment by ratnesh-maurya** [comment]
@Arnab7456
