### ISSUE TITLE
Add Search Bar to Home Remedies Section for Easy Filtering

### ISSUE THREAD

**Issue by shubhagarwal1** [Ratnesh-Team/Rehabify#69]
This PR adds a search bar to the "Home Remedies" section, allowing users to quickly filter remedies by keywords. Users can type keywords (e.g., "Exercise", "Diet") to dynamically update the displayed remedies based on matching titles or descriptions. If no matches are found, a message will inform users accordingly. This feature enhances user experience by providing an efficient way to find specific remedies, improving the overall usability of the application.
Hey @ratnesh-maurya please assign this task to me

**Comment by ratnesh-maurya** [comment]
sure go ahead

**Comment by SWITCHin2** [comment]
@ratnesh-maurya can you assign this issue to me if there is no such recent activities done in this.[gssoc-ext]

**Comment by SWITCHin2** [comment]
@ratnesh-maurya https://github.com/Ratnesh-Team/Rehabify/pull/166 Have raised aPR for the same, did it as gssoc-ext is ending soon. Hope you understand.
