### ISSUE TITLE
[FEAT]: AddingMulti-language Support in Rehabify

### ISSUE THREAD

**Issue by IkkiOcean** [Ratnesh-Team/Rehabify#70]
### Description:
We need to integrate Google Translator into the Rehabify web application to allow users to translate all pages into multiple languages. This will enhance the user experience for non-English-speaking users by providing them with an accessible interface in their preferred language.

### Tasks:

	1.	Investigate the Google Translator API or other suitable translation tools.
	2.	Integrate the translator into the main layout of the application.
	3.	Ensure translation is available for all pages
	4.	Add a language selector dropdown to the header/footer for easy language switching.
	5.	Test translations to ensure proper formatting and layout across all languages.

### Acceptance Criteria:

	•	Users should be able to translate any page to their selected language using the Google Translator integration.
	•	The layout and styling of pages should not break when the content is translated.
	•	The language selector should be accessible and functional on all pages.

### Program: GSSOC-ext and hacktoberfest
** Please add LEVEL 3 to the issue**

**Comment by ratnesh-maurya** [comment]
sure go ahead,

**Comment by IkkiOcean** [comment]
@ratnesh-maurya I'm not able to login. can you help me with it?
I tried using all the login credentials  written in readme.md

<img width="1212" alt="Screenshot 2024-10-10 at 2 49 37 PM" src="https://github.com/user-attachments/assets/90114a08-c82e-48a7-8685-339b0372a29b">



- My local server logs
```

Connected to MongoDB
[GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.

[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:   export GIN_MODE=release
 - using code:  gin.SetMode(gin.ReleaseMode)

[GIN-debug] GET    /users                    --> github.com/Ratnesh-Team/Rehabify/routes.RehabifyRoutes.GetUsers.func2 (8 handlers)
[GIN-debug] GET    /NMK                      --> github.com/Ratnesh-Team/Rehabify/routes.RehabifyRoutes.GetNMK.func4 (8 handlers)
[GIN-debug] GET    /home-remedies            --> github.com/Ratnesh-Team/Rehabify/routes.RehabifyRoutes.GetHomeremediesDetails.func6 (8 handlers)
[GIN-debug] POST   /signUp                   --> github.com/Ratnesh-Team/Rehabify/routes.RehabifyRoutes.AddUser.func7 (7 handlers)
[GIN-debug] POST   /signIn                   --> github.com/Ratnesh-Team/Rehabify/routes.RehabifyRoutes.VerifyUser.func8 (7 handlers)
[GIN-debug] GET    /doctor                   --> github.com/Ratnesh-Team/Rehabify/routes.RehabifyRoutes.GetDoctor.func10 (8 handlers)
[GIN-debug] POST   /addNmk                   --> github.com/Ratnesh-Team/Rehabify/routes.RehabifyRoutes.AddNMK.func11 (7 handlers)
[GIN-debug] POST   /addDoctor                --> github.com/Ratnesh-Team/Rehabify/routes.RehabifyRoutes.AddDoctor.func12 (7 handlers)
[GIN-debug] POST   /addPatient               --> github.com/Ratnesh-Team/Rehabify/routes.RehabifyRoutes.AddPatient.func13 (7 handlers)
[GIN-debug] POST   /NMK/approve              --> github.com/Ratnesh-Team/Rehabify/routes.RehabifyRoutes.ApproveNMK.func14 (7 handlers)
[GIN-debug] GET    /swagger-ui/*any          --> github.com/swaggo/gin-swagger.CustomWrapHandler.func1 (7 handlers)
2024/10/10 14:29:37 Server listening on http://localhost:3000/
```

**Comment by IkkiOcean** [comment]
it might be CORs issue but I'm not well versed in golang

**Comment by ratnesh-maurya** [comment]
This is due your mongodb doesn't have any data for the user 
## do you want to make changes in backend I'd yes I can provide you my db, if now just run frontend with .env file it will work

**Comment by IkkiOcean** [comment]
> This is due your mongodb doesn't have any data for the user
> 
> ## do you want to make changes in backend If yes I can provide you my db, if no just run frontend with .env file it will work

How do I bypass login page. I can enter the website without logging in. is their any other way?

**Comment by ratnesh-maurya** [comment]
@IkkiOcean  
do you want to make changes in backend code

**Comment by ratnesh-maurya** [comment]
> > @IkkiOcean do you want to make changes in backend code
> 
> no my issue is about frontend, I need to check it before working for it. how can I work on it without checking it out

make a .env file  with  this 
 VITE_BASE_URL = rehabify-production.up.railway.app
 
 and run the project you will able to login in frontend

**Comment by IkkiOcean** [comment]
> > > @IkkiOcean do you want to make changes in backend code
> > 
> > 
> > no my issue is about frontend, I need to check it before working for it. how can I work on it without checking it out
> 
> make a .env file with this VITE_BASE_URL = rehabify-production.up.railway.app
> 
> and run the project you will able to login in frontend

it still persists. I cant login and I can enter the site.

<img width="1259" alt="Screenshot 2024-10-10 at 3 55 27 PM" src="https://github.com/user-attachments/assets/8e50a94b-5045-4f4c-b70f-8a25a1a51a5b">

<img width="1272" alt="Screenshot 2024-10-10 at 2 49 06 PM" src="https://github.com/user-attachments/assets/84dad671-e8ce-4867-8aa3-6827360bce99">

**Comment by IkkiOcean** [comment]
> > > @IkkiOcean do you want to make changes in backend code
> > 
> > 
> > no my issue is about frontend, I need to check it before working for it. how can I work on it without checking it out
> 
> make a .env file with this VITE_BASE_URL = rehabify-production.up.railway.app
> 
> and run the project you will able to login in frontend

it still persists. I cant login

**Comment by ratnesh-maurya** [comment]
> > > > @IkkiOcean do you want to make changes in backend code
> > > 
> > > 
> > > no my issue is about frontend, I need to check it before working for it. how can I work on it without checking it out
> > 
> > 
> > make a .env file with this VITE_BASE_URL = rehabify-production.up.railway.app
> > and run the project you will able to login in frontend
> 
> it still persists. I cant login

can you send me network tab screenshot what is the request and response

**Comment by IkkiOcean** [comment]
> > > > > @IkkiOcean do you want to make changes in backend code
> > > > 
> > > > 
> > > > no my issue is about frontend, I need to check it before working for it. how can I work on it without checking it out
> > > 
> > > 
> > > make a .env file with this VITE_BASE_URL = rehabify-production.up.railway.app
> > > and run the project you will able to login in frontend
> > 
> > 
> > it still persists. I cant login
> 
> can you send me network tab screenshot what is the request and response


<img width="1264" alt="Screenshot 2024-10-10 at 7 08 09 PM" src="https://github.com/user-attachments/assets/81e3296d-d267-4d0d-882e-02f798faac3a">
<img width="1250" alt="Screenshot 2024-10-10 at 7 08 40 PM" src="https://github.com/user-attachments/assets/311a5200-ece9-457a-92dd-0bd2583af2d0">

**Comment by ratnesh-maurya** [comment]
use this in .emv file 
 VITE_BASE_URL =https://rehabify-production.up.railway.app

**Comment by ratnesh-maurya** [comment]
if error still not solved ping me on discord ,

**Comment by IkkiOcean** [comment]
> use this in .env file VITE_BASE_URL =https://rehabify-production.up.railway.app

thanks for you time. its working now.

**Comment by ratnesh-maurya** [comment]
Great work @IkkiOcean 🎉
