### ISSUE TITLE
As your stats section is not looking.

### ISSUE THREAD

**Issue by VinayLodhi1712** [Ratnesh-Team/Rehabify#72]
**Is your feature request related to a problem? Please describe.**
Stats section is not looking good in UI

**Describe the solution you'd like**
I will make it good looking UI and also use react countup library in it.

**Additional context**

https://github.com/user-attachments/assets/24ce7945-8e6f-419c-bb52-9b67cfcd9392

![outnup](https://github.com/user-attachments/assets/72c2ed99-fdc9-48f7-acfe-3d2a1c5cfac2)

**Comment by ratnesh-maurya** [comment]
sure go ahead

**Comment by ratnesh-maurya** [comment]
Good work @VinayLodhi1712 🎉
