### ISSUE TITLE
Google Oauth adding

### ISSUE THREAD

**Issue by krishpathak** [Ratnesh-Team/Rehabify#76]
**Is your feature request related to a problem? Please describe.**
No, it is not problem but it will help user to login with their registered email id.

**Describe the solution you'd like**
I will add Google OAuth.

**Comment by ratnesh-maurya** [comment]
Currently there is no need to migrate the authentication to google auth .
If in future if we do so we will take help from you

**Comment by ratnesh-maurya** [comment]
sure go ahead and make sure to take role while signup and make changes in backend accordingly
