### ISSUE TITLE
Add Metrics Table to README

### ISSUE THREAD

**Issue by neeru24** [Ratnesh-Team/Rehabify#77]
### Issue: Add Metrics Table to README
It would enhance the README file significantly to include a table displaying key repository metrics such as the number of stars, forks, pull requests, and any other relevant statistics. This addition will make the repository more informative and visually appealing to users.

### Benefits:

- Improves the overall presentation of the README.
- Encourages contributions by showcasing community involvement.

KINDLY ASSIGN ME THIS ISSUE

**Comment by ratnesh-maurya** [comment]
Thank you for your suggestion! 

Here are the key changes we'd like you to implement:

1.  **Main README Impact:**\
    The main `README.md` should provide an impactful overview of the project. It should include:

    -   A brief introduction of the project, including its purpose and key features.
    -   Instructions for setting up the entire project at a high level.
    -   Contribution guidelines and any necessary links for further documentation or project details.
    -   Contact information or links to issue reporting.
2.  **Frontend and Backend ReadMe Files:**\
    There should be **individual `README.md` files** inside the **`Frontend/`** and **`Backend/`** folders, clearly documenting:

    -   **Project setup:** A step-by-step guide on how to install dependencies, run the project locally, and any specific setup instructions.
    -   **Environment variables:** Clearly list all `.env` variables required for the respective frontend and backend projects. Include examples or a sample `.env` file.
    -   **Important scripts/commands:** Detail any important scripts to run (e.g., build, test, lint) that are specific to each service.
    -   Any special configurations or notes that the developers should be aware of when setting up or contributing to each part of the project.
3.  **Consistency:**\
    Ensure that the formatting and tone are consistent across all `README.md` files. The documentation should be easy to follow for both new developers and external contributors.

**Comment by ratnesh-maurya** [comment]
@neeru24 

### Please mention the following in the README.md:

- For contributing to this repository, make sure  you raise a pull request to the **develop** branch.

**Comment by ratnesh-maurya** [comment]
https://github.com/Kushal997-das/Project-Guidance

take reference from this project

**Comment by neeru24** [comment]
>  @neeru24 
> 
> ### Please mention the following in the README.md:
> 
> - For contributing to this repository, make sure  you raise a pull request to the **develop** branch.

Sure, I'll submit a PR by tonight.

**Comment by ratnesh-maurya** [comment]
Take your time and make sure you write readme by yourself , take help of AI but not copy paste from it , just a advice .

**Comment by ratnesh-maurya** [comment]
Any update @neeru24

**Comment by neeru24** [comment]
> Any update @neeru24 
> 

Yes, I've almost completed. I'll submit a PR soon
