### ISSUE TITLE
Scroll bar of your website is not looking good

### ISSUE THREAD

**Issue by VinayLodhi1712** [Ratnesh-Team/Rehabify#80]
adding a smooth suited scroll bar in place of default scroll bar on your website.

https://github.com/user-attachments/assets/8b54c4f8-5488-426c-bf33-a29d18253899

![againscroll](https://github.com/user-attachments/assets/561878ef-0344-4451-bb48-30b910c5b8f4)

**Comment by ratnesh-maurya** [comment]
Hi @VinayLodhi1712 , but i am not in motion of changing the scroll because suppose if someone of old age visit website he navigate in website with scroll bar only if become difficult for him to adapt new scroll bar , i have seen such issue
