### ISSUE TITLE
Issue Title: "Enhance Icon Quality"

### ISSUE THREAD

**Issue by AswaniBolisetti** [Ratnesh-Team/Rehabify#83]
@ratnesh-maurya 
![icon](https://github.com/user-attachments/assets/1f314e91-ad08-428e-93ad-9875508ad92f)

here the icon is not in good quality, i can enhance the quality of the icon using some tools.

Issue Description: I would like to enhance the quality of the icons used on the website. This could involve updating them to higher resolution versions, ensuring they are visually appealing and consistent across the site, and improving their relevance to the overall design.

could you please assign this issue to me under level2, hacktoberfest-accepted, gssoc

**Comment by ratnesh-maurya** [comment]
Sure go ahead we will decide the level once you raise a PR

**Comment by AswaniBolisetti** [comment]
Could you please tell me why am i not able to sign-in, the backend is
running too

i have changed the logo in sign-in page, and i want to see in the dashboard
also, but the signin is not working

**Comment by ratnesh-maurya** [comment]
you don't need to run backend as your issue is related to frontend , 
just make a .env file in frontend see sample.env file form environment variables  , then npm i , npm start 
it will work
