### ISSUE TITLE
UI enhancememt in Footer and Appointment Section

### ISSUE THREAD

**Issue by Bhum-ika** [Ratnesh-Team/Rehabify#87]
**Is your feature request related to a problem? Please describe.**
The information on both the card is displayed in a disorganized manner. There are no hover effects on the footer and "Book Appointment" button.

I have attached image for your reference. In dark mode, it is looking worse.
**Describe the solution you'd like**

 I would like to enhance its UI to make user read all the info and differentiate it in easily with proper arrangement and will fix the hover effects as well.

![image](https://github.com/user-attachments/assets/8aa9197b-c0e4-4eee-93ae-2a8d10802ecb)
![image](https://github.com/user-attachments/assets/ff6b153d-af11-4211-8f80-1e53aca7970d)
![image](https://github.com/user-attachments/assets/b5bb92a7-8b52-414c-8ff0-bd1d3bf0bdfe)

Kindly assign this issue to me under hactoberfest, gssoc-ext and relevant tags.

**Comment by ratnesh-maurya** [comment]
sure , go ahead

**Comment by Bhum-ika** [comment]
Hi @ratnesh-maurya 
![image](https://github.com/user-attachments/assets/2f12d147-d1b7-42af-afbe-45c9cd575ec2)

I followed the steps mentioned in readme but it is still giving this error

**Comment by ratnesh-maurya** [comment]
VITE_BASE_URL =https://rehabify-production.up.railway.app
 
 use this in frontend's   .env file

**Comment by Bhum-ika** [comment]
Got it, Thank you
Will raise the PR tonight!!
