### ISSUE TITLE
Adding the contributors page to mention all the awersome people who have contributed to the website.

### ISSUE THREAD

**Issue by tarunkumar2005** [Ratnesh-Team/Rehabify#88]
**Is your feature request related to a problem? Please describe.**
Adding the contributors page to mention all the awersome people who have contributed to the website.

**Describe the solution you'd like**
I will add a super awersome and professional contributors page to thanks all the people who have contributed in this repo.

@ratnesh-maurya Assign this to me under gssoc 2024 ext and hacktoberfest i will work on this issue.

**Comment by ratnesh-maurya** [comment]
can you provide me some example that how that page will look like

**Comment by tarunkumar2005** [comment]
@ratnesh-maurya here is the video demo :- 

Uploading Recording 2024-10-11 113559.mp4…

This is just a demo i will create it according to the theme and more proper

**Comment by ratnesh-maurya** [comment]
sure , go ahead ,
Make sure to add github icon in header  on clicking that user should be redirected to page which  you have made

**Comment by tarunkumar2005** [comment]
Ya i will do that

**Comment by ratnesh-maurya** [comment]
![{7133058F-9ACE-4E56-9582-BAA9A7345FAD}](https://github.com/user-attachments/assets/98b97b03-b617-4b61-b4a2-e90dff3c3a90)

**Comment by tarunkumar2005** [comment]
@ratnesh-maurya You have so many errors all the dependencies are not downloaded by npm i in frontend and also you have used ts but there are so many errors in it too like type any and so i don't know if i am only finding those or so.
