### ISSUE TITLE
using google sign in account firebase 

### ISSUE THREAD

**Issue by Joshna907** [Ratnesh-Team/Rehabify#90]
We could provide sign in with google which could ensure trust for the website also making simple to sign in rather than adding each detail 
![image](https://github.com/user-attachments/assets/560b2c81-5209-49ab-be91-86c26ba6ba16)

**Comment by ratnesh-maurya** [comment]
sure go ahead make sure to take role while signUp and make related changes in backend

**Comment by ratnesh-maurya** [comment]
Similar issue is assigned to another contributor
