### ISSUE TITLE
Adding hover effect in the treatment center page.

### ISSUE THREAD

**Issue by coderashhar** [Ratnesh-Team/Rehabify#91]
**Is your feature request related to a problem? Please describe.**
=> The cards in the treatment page does not look and feel responsive which leads to a bad user experience.

**Describe the solution you'd like**
=> I would like add hover effect to the cards to make the UI look more responsive.

**Describe alternatives you've considered**
=> actually we make all the cards more responsive by adding the hover feature.

**Additional context**
I would like to add hover effect to treatment center , Home remedies and Doctor appointment page.

@ratnesh-maurya  Kindly assign this issue to me under gssoc-extd and hackoberfest24.
<img width="1470" alt="Screenshot 2024-10-12 at 3 27 56 PM" src="https://github.com/user-attachments/assets/63d8a7d1-b424-435d-845b-de093121d4bd">

**Comment by ratnesh-maurya** [comment]
sure go ahead

**Comment by coderashhar** [comment]
thank you Ratnesh I'll keep you in the loop
