### ISSUE TITLE
Adding scroll to top feature

### ISSUE THREAD

**Issue by AswaniBolisetti** [Ratnesh-Team/Rehabify#99]
@ratnesh-maurya 
I would like to add scroll to top feature
could you please assign this issue to me

**Comment by ratnesh-maurya** [comment]
@AswaniBolisetti you have closed a issue without  raising a PR .
This is not a code of conduct to contribute in Open source

**Comment by AswaniBolisetti** [comment]
> @AswaniBolisetti you have closed a issue without raising a PR . This is not a code of conduct to contribute in Open source

sorry for that, i tried to increase the quality of the image, but in small size the resolution is same as previous, thats why i closed the issue

**Comment by ratnesh-maurya** [comment]
You should informed that first and then closed it

**Comment by AswaniBolisetti** [comment]
> You should informed that first and then closed it

@ratnesh-maurya 
Sorry for that, i don't know about it, i thought there would be no issue with that.

**Comment by ratnesh-maurya** [comment]
No issues
